version: "3.8"

services:
  cyty:
    image: postgres:15.2-alpine
    container_name: "cyty"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SSL_MODE=${SSL_MODE}
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge